# fly.toml file generated for kexobot on 2023-03-02T13:03:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kexobot"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true